name: GitHub Actions testing Docker Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

# Create image tag
    steps:
    
    
    - uses: actions/checkout@v2
      name: Check out code
