# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Build Python App

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  # Additional variables can be created using the format below.
  # The info available to the push event can be found here: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
  GITHUB_REPO: ${{ github.event.repository.name }}
  GITHUB_PUSHER_NAME: ${{ github.event.pusher.name }}
  GITHUB_PUSHER_EMAIL: ${{ github.event.pusher.email }}
  GITHUB_HEAD_COMMIT: ${{ github.event.head_commit.url}}
  GITHUB_MESG: ${{ github.event.head_commit.message }}
  GITHUB_COMPARE: ${{ github.event.compare }}
  GITHUB_VERSION: ${{ github.event.compare }}
      

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: List Downloaded Components
        run: |-
         pwd && ls -lrt
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: microservices/kycvalidator:latest


  deploy-sit:
    name: Deploy-SIT
    runs-on: ubuntu-latest
    environment: 'sit'
    needs: dockerbuild

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: CO-OPBANK/deployments
          ref: master
          fetch-depth: 0
          token: ${{ secrets.MY_GIT_TOKEN }}
      - name: Version Image to Current Deployment
        run: |-
          pwd && ls -lrt
          cd sit/kycvalidator
          pwd && ls -lrt
          currentimage=$(cat deployment.yaml | grep image: | awk -F ':' '{print $NF}')
          echo currentimage $currentimage
          #sed -i s#$value#${{ needs.docker.outputs.short_sha }}#g deployment.yaml
          cat deployment.yaml | grep image:
